# Generated by Django 4.1.2 on 2023-08-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
