# Generated by Django 4.1.2 on 2023-08-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0002_alter_region_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id_set', serialize=False, to='stc.users', unique=True),
        ),
    ]
