# Generated by Django 4.1.2 on 2023-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0003_alter_user_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('internal_doc_no', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('storage_location', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('document_date', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('case_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('court', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('var_text1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text4', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text5', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text6', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_text7', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('var_text8', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('loadingCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('packingCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('landing_charge', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('other_fines', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('totsale', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('trasferPostDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('trasferSavedDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('printed', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='master_data',
            fields=[
                ('material_no', models.IntegerField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('girth', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('reduced_volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('visible_material_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('qr_id', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('timber_class', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('specis', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.IntegerField(blank=True, default=None, null=True)),
                ('lot_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('value_grade', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('value_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('transCost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('depot', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('doc_date', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('gradeInCoupe', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('soldGrade', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('workingSheetNo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('auctionLotSheetNo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, max_length=10, null=True)),
                ('yiel_d', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, max_length=10, null=True)),
                ('logType', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
