# Generated by Django 4.1.2 on 2023-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0004_document_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='movement',
            fields=[
                ('material_no', models.IntegerField(primary_key=True, serialize=False)),
                ('movement', models.IntegerField(blank=True, default=None, null=True)),
                ('old_ref_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('new_ref_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('bin', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('document_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('valueGrade', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='master_data',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
