# Generated by Django 4.1.2 on 2023-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0005_movement_alter_master_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_data',
            name='material_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
